name: byaz_track
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+4

environment:
  sdk: ">=3.7.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animated_bottom_navigation_bar: ^1.4.0
  cached_network_image: ^3.4.1
  calendar_date_picker2: ^2.0.0
  chewie: ^1.11.3
  cloud_firestore: ^5.6.12
  cupertino_icons: ^1.0.8
  custom_refresh_indicator: ^4.0.1
  dartz: ^0.10.1
  device_info_plus: ^11.5.0
  dio: ^5.8.0+1
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.4.2
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  firebase_storage: ^12.4.10
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_local_notifications: ^19.3.1
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.1.0
  flutter_widget_from_html: ^0.16.0
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.1
  gallery_saver_plus: ^3.2.9
  geolocator: ^14.0.2
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  google_places_autocomplete_text_field: ^1.1.0
  http_parser: ^4.1.2
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  flutter_keyboard_visibility: ^6.0.0
  loading_animation_widget: ^1.3.0
  logger: ^2.6.1
  material_2_switch: ^1.0.0
  mime_type: ^1.0.1
  permission_handler: ^12.0.0+1
  persistent_bottom_nav_bar_v2: ^5.3.1
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  toggle_switch: ^2.3.0
  url_launcher: ^6.3.2
  video_player: ^2.9.5
  file_picker: ^10.3.2
  flutter_linkify: ^6.0.0
  # logger: ^2.6.1
  # mime_type: ^1.0.1
  # http_parser: ^4.1.2
  # google_places_autocomplete_text_field: ^1.1.0
  # cloud_firestore: ^5.6.12
  # firebase_storage: ^12.4.10
  connectivity_plus: ^6.1.5
  syncfusion_flutter_pdfviewer: ^31.1.17
  path_provider: ^2.1.5
  image: ^4.5.4
  googleapis_auth: ^2.0.0
  shimmer: ^3.0.0
  google_places_flutter: ^2.1.1
  geocoding: ^4.0.0
  app_links: ^6.4.1
  share_plus: ^12.0.0
  linkify: ^5.0.0
  font_awesome_flutter:
  get_storage: ^2.1.1
  flutter_localizations:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  # fl_chart: ^0.68.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_flavorizr: ^2.4.0
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  adaptive_icon_background: "#ffffff"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Fonseca
      fonts:
        - asset: assets/fonts/Fonseca.otf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_18pt-Black.ttf
          weight: 900

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
